fos_rest:
    param_fetcher_listener: true
    view:
        empty_content: 200
        view_response_listener: true
        failed_validation: HTTP_BAD_REQUEST
        formats:
            json: true
            xml: false
    body_listener:
        decoders:
            json: fos_rest.decoder.json
    format_listener:
        rules:
            - { path: '/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: '^/', stop: true, fallback_format:  html }
    exception:
        enabled: true
    serializer:
        serialize_null: true