App\Entity\Book:
    attributes:
        id:
            groups: ['book']
        title:
            groups: ['book']
        image:
            groups: ['book']
        categories:
            groups: ['book']
        description:
            groups: ['book']
        score:
            groups: ['book']

